# Dependencies

source:         "."
url:            "https://italia.github.io/design-comuni-prototipi"
baseurl:        "/design-comuni-prototipi"
destination:    ./_site
encoding:       UTF-8
exclude:
  - .git/
  - .github/
  - AUTHORS
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - cover-image.png
  - LICENSE.md
  - Gemfile
  - Gemfile.lock
  - README.md
  - "*.sketch"

plugins:
  - jekyll-redirect-from
  - jekyll-feed

whitelist:
  - jekyll-redirect-from

google_analytics: UA-145094697-1
jekyll_version: 4.2.0
